[package]
name = "mygui"
version = "0.1.0"
authors = ["kivimango <balazsviktor23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font-kit = "0.10.0"
specs = { version = "0.16.1", features = ["specs-derive"] }
minifb = "0.19.2"
tiny-skia = "0.5.1"
orbclient = "0.3.31"

pathfinder_geometry = "0.5.1"